import { useMemo, useState } from "react";
import { CalendarClock, CheckCircle2, Lightbulb, Plus, Sparkles, Target } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import {
  actionQuadrant,
  actionScore,
  useActions,
  useCreateAction,
  useToggleAction,
  type ActionItem,
} from "@/hooks/useActions";
import { AgendarAcaoAvulsaModal } from "@/components/actions/AgendarAcaoAvulsaModal";
import { toast } from "sonner";

const AREAS = ["Clínica", "Mentoria", "Pessoal"];
const QUADRANT_STYLE: Record<string, { color: string; soft: string }> = {
  "Fazer primeiro": { color: "var(--color-green)", soft: "var(--color-green-bg)" },
  Planejar: { color: "var(--brand-navy)", soft: "var(--brand-navy-soft)" },
  Encaixar: { color: "var(--brand-accent)", soft: "var(--brand-accent-soft)" },
  Reavaliar: { color: "var(--color-red)", soft: "var(--color-red-bg)" },
};

export default function ActionsPage() {
  const { data: actions, isLoading } = useActions();
  const toggle = useToggleAction();
  const [open, setOpen] = useState(false);
  const [agendar, setAgendar] = useState<ActionItem | null>(null);
  const ranked = useMemo(() => [...(actions ?? [])].sort((a, b) => actionScore(b) - actionScore(a)), [actions]);
  return <AppShell><div className="performance-page space-y-6">
    <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="eyebrow mb-2">DECISÃO E PRIORIZAÇÃO</div><h1 className="font-display text-3xl font-semibold">Matriz impacto × esforço</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Registre demandas avulsas e descubra objetivamente o que deve entrar primeiro na sua semana.</p></div><Button className="brand-button" onClick={() => setOpen(true)}><Plus className="mr-2 h-4 w-4" />Nova ação</Button></header>
    <section className="performance-card p-4 md:p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-display text-xl font-semibold">Mapa de prioridades</h2><p className="text-xs text-muted-foreground">Quanto mais acima e à esquerda, maior o retorno com menor esforço.</p></div><div className="rounded-full bg-[var(--brand-primary-soft)] px-3 py-1 text-xs font-semibold text-[var(--brand-primary)]">Impacto 0–10 · Esforço 0–10</div></div><div className="relative h-[460px] overflow-hidden rounded-2xl border bg-[var(--brand-light)]"><div className="absolute inset-x-1/2 inset-y-0 w-px bg-border" /><div className="absolute inset-y-1/2 inset-x-0 h-px bg-border" /><Quadrant label="FAZER PRIMEIRO" className="left-4 top-4" color="var(--color-green)" /><Quadrant label="PLANEJAR" className="right-4 top-4" color="var(--brand-navy)" /><Quadrant label="ENCAIXAR" className="bottom-4 left-4" color="var(--brand-accent)" /><Quadrant label="REAVALIAR" className="bottom-4 right-4" color="var(--color-red)" /><span className="absolute left-2 top-1/2 -translate-y-1/2 -rotate-90 text-[9px] font-bold uppercase tracking-widest text-muted-foreground">Impacto →</span><span className="absolute bottom-1 left-1/2 -translate-x-1/2 text-[9px] font-bold uppercase tracking-widest text-muted-foreground">Esforço →</span>{ranked.filter(a => !a.concluida).map((action, index) => { const quadrant = actionQuadrant(action); const style = QUADRANT_STYLE[quadrant]; return <button key={action.id} title={`${action.descricao} · impacto ${action.impacto} · esforço ${action.esforco}`} className="absolute flex h-9 w-9 -translate-x-1/2 translate-y-1/2 items-center justify-center rounded-full border-2 border-white text-xs font-bold text-white shadow-lg transition hover:z-20 hover:scale-125" style={{ left: `${6 + action.esforco * 8.8}%`, bottom: `${5 + action.impacto * 8.8}%`, background: style.color }}>{index + 1}</button>; })}</div></section>
    <section><div className="mb-3"><h2 className="font-display text-xl font-semibold">Ranking estratégico</h2><p className="text-xs text-muted-foreground">Ordenado por impacto × (11 − esforço).</p></div><div className="performance-card overflow-hidden">{isLoading ? <div className="p-8 text-center text-sm text-muted-foreground">Carregando...</div> : ranked.length === 0 ? <div className="flex flex-col items-center p-10 text-center"><Lightbulb className="mb-3 h-8 w-8 text-[var(--brand-accent)]" /><h3 className="font-display text-lg font-semibold">Nenhuma ação avulsa</h3><p className="mt-1 text-sm text-muted-foreground">Registre aquela demanda importante que ainda não pertence a uma meta.</p></div> : <div className="divide-y">{ranked.map((action, index) => { const quadrant = actionQuadrant(action); const style = QUADRANT_STYLE[quadrant]; return <div key={action.id} className={`grid gap-3 p-4 md:grid-cols-[48px_1fr_110px_110px_130px] md:items-center ${action.concluida ? "opacity-50" : ""}`}><div className="font-display text-2xl text-muted-foreground/50">{String(index + 1).padStart(2, "0")}</div><div className="flex items-start gap-3"><Checkbox checked={action.concluida} onCheckedChange={(v) => toggle.mutate({ id: action.id, concluida: v === true })} className="mt-0.5" /><div><div className={`text-sm font-semibold ${action.concluida ? "line-through" : ""}`}>{action.descricao}</div><div className="mt-1 text-xs text-muted-foreground">{action.area}{action.prazo ? ` · ${new Date(`${action.prazo}T12:00:00`).toLocaleDateString("pt-BR")}` : " · sem prazo"}</div>{!action.concluida && <Button size="sm" variant="ghost" className="mt-2 h-7 px-2 text-xs" onClick={() => setAgendar(action)}><CalendarClock className="mr-1.5 h-3.5 w-3.5" />{action.data_agendada && action.hora_inicio ? `${new Date(`${action.data_agendada}T12:00:00`).toLocaleDateString("pt-BR")} às ${action.hora_inicio.slice(0, 5)}` : "Colocar na semana"}</Button>}</div></div><Score label="Impacto" value={action.impacto} /><Score label="Esforço" value={action.esforco} /><span className="w-fit rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider" style={{ color: style.color, background: style.soft }}>{quadrant}</span></div>; })}</div>}</div></section>
    <NewActionModal open={open} onOpenChange={setOpen} onCreated={setAgendar} />
    <AgendarAcaoAvulsaModal
      open={!!agendar}
      onOpenChange={(value) => !value && setAgendar(null)}
      action={agendar}
    />
  </div></AppShell>;
}

function Quadrant({ label, className, color }: { label: string; className: string; color: string }) { return <span className={`absolute text-[10px] font-bold tracking-[0.14em] ${className}`} style={{ color }}>{label}</span>; }
function Score({ label, value }: { label: string; value: number }) { return <div><div className="text-[9px] font-bold uppercase tracking-wider text-muted-foreground">{label}</div><div className="mt-1 flex items-center gap-2"><strong className="font-display text-xl">{value}</strong><div className="h-1.5 flex-1 rounded-full bg-muted"><div className="h-full rounded-full bg-[var(--brand-accent)]" style={{ width: `${value * 10}%` }} /></div></div></div>; }
function NewActionModal({ open, onOpenChange, onCreated }: { open: boolean; onOpenChange: (value: boolean) => void; onCreated: (action: ActionItem) => void }) { const create = useCreateAction(); const [descricao, setDescricao] = useState(""); const [area, setArea] = useState("Pessoal"); const [impacto, setImpacto] = useState(7); const [esforco, setEsforco] = useState(3); const [prazo, setPrazo] = useState(""); const quadrant = actionQuadrant({ impacto, esforco }); const submit = async () => { if (!descricao.trim()) return; try { const created = await create.mutateAsync({ descricao: descricao.trim(), area, impacto, esforco, prazo: prazo || null }); toast.success("Ação adicionada à matriz"); setDescricao(""); setImpacto(7); setEsforco(3); setPrazo(""); onOpenChange(false); onCreated(created); } catch (e) { toast.error(e instanceof Error ? e.message : "Não foi possível salvar"); } }; return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle className="font-display text-2xl">Nova ação avulsa</DialogTitle><DialogDescription>Ela não precisa estar vinculada a uma meta. Avalie retorno e esforço para priorizar.</DialogDescription></DialogHeader><div className="space-y-5 pt-2"><div><Label>O que precisa ser feito?</Label><Input className="mt-2" value={descricao} onChange={(e) => setDescricao(e.target.value)} placeholder="Ex.: criar página de vendas da mentoria" /></div><div className="grid grid-cols-2 gap-3"><div><Label>Área</Label><Select value={area} onValueChange={setArea}><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent>{AREAS.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div><Label>Prazo opcional</Label><Input type="date" className="mt-2" value={prazo} onChange={(e) => setPrazo(e.target.value)} /></div></div><Rating label="Impacto no resultado" value={impacto} onChange={setImpacto} low="Baixo retorno" high="Alto retorno" /><Rating label="Esforço para executar" value={esforco} onChange={setEsforco} low="Pouco esforço" high="Muito esforço" /><div className="rounded-xl p-4" style={{ background: QUADRANT_STYLE[quadrant].soft, color: QUADRANT_STYLE[quadrant].color }}><div className="text-[10px] font-bold uppercase tracking-wider">Classificação automática</div><div className="font-display mt-1 text-xl font-semibold">{quadrant}</div><div className="mt-1 text-xs">Pontuação estratégica: {impacto * (11 - esforco)} de 100</div></div><Button className="brand-button w-full" disabled={!descricao.trim() || create.isPending} onClick={submit}><Sparkles className="mr-2 h-4 w-4" />Adicionar e priorizar</Button></div></DialogContent></Dialog>; }
function Rating({ label, value, onChange, low, high }: { label: string; value: number; onChange: (value: number) => void; low: string; high: string }) { return <div><div className="mb-3 flex items-center justify-between"><Label>{label}</Label><span className="font-display text-2xl font-semibold text-[var(--brand-primary)]">{value}</span></div><Slider value={[value]} min={0} max={10} step={1} onValueChange={(v) => onChange(v[0])} /><div className="mt-2 flex justify-between text-[10px] text-muted-foreground"><span>{low}</span><span>{high}</span></div></div>; }
