import { useMemo, useState } from "react";
import { Check, CheckCircle2, ChevronRight, ClipboardCheck, RotateCcw, Save, Sparkles, Target } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { usePlanos, useToggleTarefa } from "@/hooks/usePlanos";
import { toast } from "sonner";

type PlanningState = { wins: string; pending: string; lesson: string; focus: string; priorityIds: string[]; savedAt?: string };
const defaultState: PlanningState = { wins: "", pending: "", lesson: "", focus: "", priorityIds: [] };
const storageKey = () => { const now = new Date(); const first = new Date(now.getFullYear(), 0, 1); const week = Math.ceil((((now.getTime() - first.getTime()) / 86400000) + first.getDay() + 1) / 7); return `performance-week-${now.getFullYear()}-${week}`; };

export default function WeeklyPlanningPage() {
  const { data: planos } = usePlanos();
  const toggle = useToggleTarefa();
  const [step, setStep] = useState(1);
  const [state, setState] = useState<PlanningState>(() => { try { return JSON.parse(localStorage.getItem(storageKey()) ?? "null") ?? defaultState; } catch { return defaultState; } });
  const tasks = useMemo(() => (planos ?? []).flatMap((plano) => plano.tarefas.filter((task) => !task.concluida).map((task) => ({ ...task, plano: plano.titulo, area: plano.meta?.area ?? "Pessoal", meta: plano.meta?.nome ?? null }))).sort((a, b) => (a.prazo ?? "9999").localeCompare(b.prazo ?? "9999")), [planos]);
  const completed = useMemo(() => (planos ?? []).flatMap((p) => p.tarefas).filter((t) => t.concluida).length, [planos]);
  const all = useMemo(() => (planos ?? []).flatMap((p) => p.tarefas).length, [planos]);
  const execution = all ? Math.round((completed / all) * 100) : 0;
  const selectPriority = (id: string) => setState((current) => current.priorityIds.includes(id) ? { ...current, priorityIds: current.priorityIds.filter((item) => item !== id) } : current.priorityIds.length < 3 ? { ...current, priorityIds: [...current.priorityIds, id] } : current);
  const save = () => { const next = { ...state, savedAt: new Date().toISOString() }; localStorage.setItem(storageKey(), JSON.stringify(next)); setState(next); toast.success("Planejamento semanal salvo"); setStep(4); };

  return <AppShell><div className="performance-page mx-auto max-w-5xl space-y-6">
    <header><div className="eyebrow mb-2">RITUAL DE DOMINGO</div><h1 className="font-display text-3xl font-semibold">Planejamento semanal</h1><p className="mt-1 text-sm text-muted-foreground">Revise, escolha seu foco e comece a semana com clareza.</p></header>
    <div className="grid gap-3 sm:grid-cols-3"><MiniMetric label="Execução atual" value={`${execution}%`} /><MiniMetric label="Ações concluídas" value={`${completed}/${all}`} /><MiniMetric label="Prioridades definidas" value={`${state.priorityIds.length}/3`} /></div>
    <div className="flex items-center overflow-x-auto rounded-xl border bg-card p-2">{["Revisar", "Priorizar", "Planejar", "Confirmar"].map((label, index) => { const number = index + 1; const active = step === number; const done = step > number; return <div key={label} className="flex flex-1 items-center"><button onClick={() => setStep(number)} className={`flex min-w-max items-center gap-2 rounded-lg px-3 py-2 text-xs font-semibold ${active ? "bg-[var(--brand-dark)] text-white" : "text-muted-foreground"}`}><span className={`flex h-5 w-5 items-center justify-center rounded-full text-[10px] ${done ? "bg-[var(--color-green)] text-white" : active ? "bg-white/20" : "bg-muted"}`}>{done ? <Check className="h-3 w-3" /> : number}</span>{label}</button>{index < 3 && <ChevronRight className="mx-1 h-4 w-4 shrink-0 text-muted-foreground/40" />}</div>; })}</div>

    {step === 1 && <div className="space-y-4"><Panel icon={<RotateCcw className="h-5 w-5" />} title="Revisão da semana" subtitle="Antes de acelerar, entenda o que aconteceu."><Field label="Quais foram suas principais conquistas?" value={state.wins} onChange={(wins) => setState({ ...state, wins })} placeholder="Resultados, entregas e avanços..." /><Field label="O que ficou pendente e por quê?" value={state.pending} onChange={(pending) => setState({ ...state, pending })} placeholder="Pendências, bloqueios e decisões..." /><Field label="Qual foi o principal aprendizado?" value={state.lesson} onChange={(lesson) => setState({ ...state, lesson })} placeholder="O que você fará diferente na próxima semana?" /></Panel><Next onClick={() => setStep(2)} /></div>}
    {step === 2 && <div className="space-y-4"><Panel icon={<Target className="h-5 w-5" />} title="Escolha três prioridades" subtitle="Prioridade demais vira apenas uma lista. Selecione no máximo três ações."><div className="grid gap-2 md:grid-cols-2">{tasks.length === 0 ? <div className="col-span-2 rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">Crie tarefas nos planos de ação para definir suas prioridades.</div> : tasks.map((task) => { const selected = state.priorityIds.includes(task.id); return <button key={task.id} onClick={() => selectPriority(task.id)} className={`rounded-xl border p-4 text-left transition ${selected ? "border-[var(--brand-accent)] bg-[var(--brand-accent-soft)]" : "bg-card hover:border-[var(--brand-primary)]/40"}`}><div className="flex items-start gap-3"><span className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full border ${selected ? "border-[var(--brand-accent)] bg-[var(--brand-accent)] text-white" : ""}`}>{selected && <Check className="h-3 w-3" />}</span><div><div className="text-sm font-semibold">{task.descricao}</div><div className="mt-1 text-xs text-muted-foreground">{task.area} · {task.plano}{task.prazo ? ` · ${new Date(`${task.prazo}T12:00:00`).toLocaleDateString("pt-BR")}` : ""}</div></div></div></button>; })}</div></Panel><Next disabled={state.priorityIds.length === 0} onClick={() => setStep(3)} /></div>}
    {step === 3 && <div className="space-y-4"><Panel icon={<ClipboardCheck className="h-5 w-5" />} title="Defina a intenção da semana" subtitle="Uma frase clara para orientar suas decisões."><Field label="Ao final desta semana, o que precisa estar diferente?" value={state.focus} onChange={(focus) => setState({ ...state, focus })} placeholder="Ex.: campanha publicada, módulo gravado e três treinos concluídos." /><div className="mt-5 rounded-xl bg-[var(--brand-primary-soft)] p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-[var(--brand-primary)]">Suas prioridades</div><div className="mt-3 space-y-2">{state.priorityIds.map((id, index) => { const task = tasks.find((item) => item.id === id); return task ? <div key={id} className="flex items-center gap-3 text-sm"><span className="font-display text-lg text-[var(--brand-accent)]">0{index + 1}</span><span className="font-medium">{task.descricao}</span></div> : null; })}</div></div></Panel><div className="flex justify-end"><Button onClick={save} className="brand-button" disabled={!state.focus.trim()}><Save className="mr-2 h-4 w-4" />Confirmar planejamento</Button></div></div>}
    {step === 4 && <div className="performance-card flex flex-col items-center p-10 text-center"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-[var(--color-green-bg)] text-[var(--color-green)]"><CheckCircle2 className="h-7 w-7" /></div><h2 className="font-display mt-4 text-2xl font-semibold">Semana planejada</h2><p className="mt-2 max-w-lg text-sm text-muted-foreground">Você definiu {state.priorityIds.length} prioridades. Agora proteja espaço na agenda e execute antes de adicionar novas demandas.</p><div className="mt-6 w-full max-w-xl rounded-xl bg-[var(--brand-light)] p-5 text-left"><div className="text-[10px] font-bold uppercase tracking-wider text-[var(--brand-accent)]">Foco da semana</div><p className="mt-2 text-sm font-medium">{state.focus}</p></div><Button variant="outline" onClick={() => setStep(1)} className="mt-6">Revisar planejamento</Button></div>}
  </div></AppShell>;
}

function Panel({ icon, title, subtitle, children }: { icon: React.ReactNode; title: string; subtitle: string; children: React.ReactNode }) { return <section className="performance-card p-5 md:p-7"><div className="mb-6 flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[var(--brand-accent-soft)] text-[var(--brand-accent)]">{icon}</div><div><h2 className="font-display text-xl font-semibold">{title}</h2><p className="mt-0.5 text-xs text-muted-foreground">{subtitle}</p></div></div>{children}</section>; }
function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="mb-5 block last:mb-0"><span className="mb-2 block text-sm font-semibold">{label}</span><Textarea value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="min-h-24 resize-none" /></label>; }
function Next({ onClick, disabled }: { onClick: () => void; disabled?: boolean }) { return <div className="flex justify-end"><Button onClick={onClick} disabled={disabled} className="brand-button">Continuar<ChevronRight className="ml-2 h-4 w-4" /></Button></div>; }
function MiniMetric({ label, value }: { label: string; value: string }) { return <div className="performance-card p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</div><div className="font-display mt-1 text-2xl font-semibold text-[var(--brand-primary)]">{value}</div></div>; }
